"""
Vault Service.

Integrates natively with the Supabase Vault `pgsodium` extension via
secure PostgreSQL RPC functions `vault_encrypt_token` and `vault_decrypt_token`.
"""

from app.services.supabase import get_supabase_client

def encrypt_token(plaintext: str) -> str:
    """
    Encrypts a token using Supabase Vault via the vault_encrypt_token RPC.
    Returns the UUID generated by the Vault secret.
    """
    if not plaintext:
        return ""
        
    supabase = get_supabase_client()
    response = supabase.rpc("vault_encrypt_token", {"secret_text": plaintext}).execute()
    
    if not response.data:
        raise ValueError("Failed to encrypt token: vault_encrypt_token RPC returned no data")
        
    return response.data

def decrypt_token(ciphertext: str) -> str:
    """
    Decrypts a token using Supabase Vault via the vault_decrypt_token RPC.
    Expects the Vault secret UUID.
    """
    if not ciphertext:
        return ""
        
    # Backwards compatibility for the old generic stub format
    if ciphertext.startswith("encrypted(") and ciphertext.endswith(")"):
        return ciphertext[10:-1]
        
    # If the token starts with the Fernet 'gAAAAAB', then we're stuck because
    # we don't have the key anymore to decrypt it, but we assume the user is wiping their test connection.
    if ciphertext.startswith("gAAAAAB"):
        raise ValueError("Legacy Fernet encrypted token encountered. Cannot decrypt without ENCRYPTION_KEY.")
        
    supabase = get_supabase_client()
    response = supabase.rpc("vault_decrypt_token", {"secret_id_text": ciphertext}).execute()
    
    if not response.data:
        # If vault doesn't find it, it might return None
        return ""
        
    return response.data

